###token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE3Njg0NDY3LCJleHAiOjE3MTgyODkyNjd9.Y_KBxM3CddxFZILXw0b2il4XtiVL8AfKBk_VUvOf8qk

###register
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Kiranto",
    "userName": "kiranta",
    "password": "1234567"
}

###login
POST http://localhost:3000/login
Content-Type: application/json

{
    "userName": "kirani",
    "password": "1234567"
}

###GET users
GET http://localhost:3000/users

###GET user by username
GET http://localhost:3000/users/kirani
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE3Njg0NDY3LCJleHAiOjE3MTgyODkyNjd9.Y_KBxM3CddxFZILXw0b2il4XtiVL8AfKBk_VUvOf8qk

###UPDATE user
PUT http://localhost:3000/users/kirani
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE3Njg0NDY3LCJleHAiOjE3MTgyODkyNjd9.Y_KBxM3CddxFZILXw0b2il4XtiVL8AfKBk_VUvOf8qk
Content-Type: application/json

{
    "name": "Kirani Yanto",
    "status": "ada"
}


###Get message
GET http://localhost:3000/message/kirani&gustiopro
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE3Njg0NDY3LCJleHAiOjE3MTgyODkyNjd9.Y_KBxM3CddxFZILXw0b2il4XtiVL8AfKBk_VUvOf8qk

###Send message
POST http://localhost:3000/message/kirani&gustiopro
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE3Njg0NDY3LCJleHAiOjE3MTgyODkyNjd9.Y_KBxM3CddxFZILXw0b2il4XtiVL8AfKBk_VUvOf8qk
Content-Type: application/json

{
    "message": "halo juga"
}

###UPDATE user
PUT http://localhost:3000/message/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE4NDIwMzE2LCJleHAiOjE3MTkwMjUxMTZ9.2ZVM8vbMGCmaPk0PAlAsb245t5tZp4AMWcy402CkbPM
Content-Type: application/json

{
    "read": "read"
}